name: guardpayfront
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.4.3'

dependencies:
  flutter:
    sdk: flutter

  # 🔹 외부 패키지들
  flutter_web_auth_2: ^4.1.0
  flutter_dotenv: ^5.1.0
  kakao_flutter_sdk_user: ^1.9.1+2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.0.0-beta.26
  #kakao_map_plugin: ^0.3.2  # 혹은 최신 버전
  webview_flutter: ^4.4.2
  shelf: ^1.4.1  # ✅ 추가
  shelf_static: ^1.1.2  # ✅ 추가
  barcode_widget: ^2.0.4

  # ✅ 이미지 선택 관련 패키지 (갤러리/카메라)
  image_picker: ^1.1.2

  # ✅ 파일 경로 및 저장 관련
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

